# Generated by Django 5.0.7 on 2024-07-11 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default settings', max_length=220)),
                ('day_shift_hours', models.IntegerField(default=8, verbose_name='shift hours')),
                ('flexible_start_time', models.TimeField(verbose_name='flexible start time range')),
                ('flexible_end_time', models.TimeField(verbose_name='flexible end time range')),
                ('shift_start', models.TimeField(default=datetime.time(8, 0), verbose_name='shift start time')),
                ('shift_end', models.TimeField(default=datetime.time(4, 30), verbose_name='shift end time')),
            ],
            options={
                'verbose_name': 'Core settings',
                'verbose_name_plural': 'Core settings',
            },
        ),
    ]
