# Generated by Django 5.0.7 on 2024-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='core',
            name='users_default_image',
            field=models.ImageField(default='temp.jpg', upload_to='media/default/', verbose_name='default image'),
            preserve_default=False,
        ),
    ]
