# Generated by Django 5.0.7 on 2024-07-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.department', verbose_name='employe department'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, max_length=5, null=True, upload_to='employe-imges/', verbose_name='employe image'),
        ),
    ]
