# Generated by Django 5.0.7 on 2024-07-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_employe_department_alter_employe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.TimeField(auto_created=True, verbose_name='punch out time')),
                ('in_time', models.TimeField(auto_now_add=True, verbose_name='punch in  time')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('type', models.CharField(default='day shift', max_length=120, verbose_name='type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
